name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  job1:
    name: Test Homebrew-Linux A-D
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/[a-d]*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done

  job2:
    name: Test Homebrew-Linux E-K
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/[e-k]*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done

  job3:
    name: Test Homebrew-Linux L-Q
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/[l-q]*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done

  job4:
    name: Test Homebrew-Linux R-T
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/[r-t]*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done

  job5:
    name: Test Homebrew-Linux U-Z
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/[u-z]*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done
