name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test Homebrew-Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/linux
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-linux
          for formula in Formula/*.rb; do
              echo "ivaquero/linux/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done
